Hooks allowed to work even when context isn't returned
fhammerl/runner-hooks pull request #56
Opened 2022-04-15 13:52 UTC by ruvceskistefan

Closes #51

2022-04-15 15:07 UTC, thboop commented on src/Runner.Worker/Handlers/StepHost.cs
> +            if (!FeatureFlagManager.IsHookFeatureEnabled())
We should check here if the hook feature is enabled and the user has opted into using it by setting the env variable.

2022-04-15 15:09 UTC, thboop commented on src/Runner.Worker/Container/ContainerHooks/ContainerHookManager.cs
> +                context.JobContext.Container["id"] = new StringContextData(response.Context.Container.Id);
any of these fields could be null even if context is not null.

I think we will have to do checks for each field, 

```
if ( response.Context.Container)
{
  if (response.Context.Container.Id)
  {
     context.JobContext.Container["id"] = new StringContextData(response.Context.Container.Id);
  }
    if (response.Context.Container.Network)
   {
// ...
   } 
}
```

2022-04-15 15:10 UTC, thboop commented on src/Runner.Worker/ActionRunner.cs
> +                if (!FeatureFlagManager.IsHookFeatureEnabled())
The feature flag just lets the user opt into the feature, I think we also want to check if they have set the env to use custom hooks as well

2022-04-17 23:40 UTC, thboop commented on src/Runner.Worker/Container/ContainerHooks/ContainerHookManager.cs
> +                    context.JobContext["hook_state"] = new StringContextData(JsonUtility.ToString(response.State));
I don't think this should be in this if statement, but we may want to wrap it in a 

```
if (response.State)
```
block

2022-04-21 12:15 UTC, fhammerl commented on src/Runner.Common/Constants.cs
> +            public static readonly string CustomHooksPath = "ACTIONS_RUNNER_CONTAINER_HOOK";
Let's use `ContainerHooksPath` (might not have existed when you forked at first :) )

2022-04-21 12:16 UTC, fhammerl commented on src/Runner.Worker/Container/FeatureFlagManager.cs
> +
Let's use the method above (same as for `ContainerHooksPath` before)

2022-04-21 12:23 UTC, fhammerl commented on src/Runner.Worker/Container/ContainerHooks/ContainerHookManager.cs
> +            if (response.Context != null)
Could we use `response?.Context?.[propName]?.` to simplify these `if`s to avoid nesting this deep?

2022-04-21 12:24 UTC, fhammerl commented on src/Runner.Worker/Container/ContainerHooks/ContainerHookManager.cs
> +            if ((object)response.State != null)
If `context.JobContext["hook_state"]` is null, will it fail when we [serialize it](https://github.com/fhammerl/runner-hooks/pull/56/files?diff=split&w=1#diff-a6fa655b45ddbf3a069e7e1ca20d62f8e405d115c2223da1d19c40b9ff24c2baR119)?

2022-04-21 12:25 UTC, fhammerl commented on src/Runner.Worker/Container/ContainerHooks/ContainerHookManager.cs
> +            if ((object)response.State != null)
The `hookState.ToString` part I mean

2022-04-21 14:27 UTC, fhammerl requested changes
LGTM

2022-04-21 14:27 UTC, fhammerl commented on src/Runner.Worker/Container/ContainerHooks/ContainerHookManager.cs
>              // TODO: Should we throw if response.Context is null or just noop?
```suggestion
```

2022-04-22 09:46 UTC, merged